fpl:
  target: dev           # default target
  outputs:
    dev:
      type: postgres
      host: postgres
      user: analytics_user
      password: pw
      port: 5432
      dbname: analytics
      schema: public
      threads: 4
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      port: 5432
      dbname: fpl_prod
      schema: public
      threads: 8
