services:
  postgres_container:
    build:
      context: .     # Folder with Dockerfile
      dockerfile: ./docker/container__postgres/Dockerfile
    ports:
      - "5432:5432" # not needed for docker networking, just if I want to docker exec into the container
    environment:
      POSTGRES_USER: local_testing
      POSTGRES_PASSWORD: local_testing_password
      POSTGRES_DB: database
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  scripts_container:
    build:
      context: .
      dockerfile: docker/container__scripts/Dockerfile
    command: poetry run dagster api grpc -h 0.0.0.0 -p 4000 -m data_platform
    ports:
      - "4000:4000"
    volumes: 
      - ./scripts:/work_dir
      - ./.dbt:/root/.dbt:ro 
    working_dir: /work_dir
    depends_on:
      - postgres_container
      - dagster-webserver
      - dagster-daemon
    environment:
      DB_HOST: postgres
   # command: sleep infinity

  dagster-webserver:
    image: dagster/dagster:1.10.0
    command: dagster-webserver -h 0.0.0.0 -p 3000 -w workspace.yaml
    ports:
      - "3000:3000"

  dagster-daemon:
    image: dagster/dagster:1.10.0
    command: dagster-daemon run

volumes:
  pgdata:
