WITH latest_import AS (

    SELECT *
    FROM {{ ref('stg_fpl__latest_import') }}
    WHERE endpoint = 'bootstrap-static/'
),

elements_ AS (

SELECT
    li.imported_at,
    li.id AS import_id,
    endpoint AS api_endpoint,
    e.*
FROM latest_import li,
LATERAL jsonb_to_recordset(raw_json->'elements') AS e(
    id int,
    bps int,
    code int,
    form text,
    news text,
    team int,
    bonus int,
    photo text,
    saves int,
    region int,
    starts int,
    status text,
    threat text,
    assists int,
    ep_next text,
    ep_this text,
    minutes int,
    removed boolean,
    special boolean,
    tackles int,
    now_cost int,
    web_name text,
    form_rank int,
    ict_index text,
    influence text,
    opta_code text,
    own_goals int,
    red_cards int,
    team_code int,
    birth_date date,
    can_select boolean,
    creativity text,
    first_name text,
    known_name text,
    news_added date,
    recoveries int,
    value_form text,
    scout_risks jsonb,
    second_name text,
    threat_rank int,
    can_transact boolean,
    clean_sheets int,
    element_type int,
    event_points int,
    goals_scored int,
    in_dreamteam boolean,
    saves_per_90 numeric,
    squad_number int,
    total_points int,
    transfers_in bigint,
    value_season text,
    yellow_cards int,
    now_cost_rank int,
    selected_rank int,
    starts_per_90 numeric,
    transfers_out bigint,
    expected_goals text,
    form_rank_type int,
    goals_conceded int,
    ict_index_rank int,
    influence_rank int,
    penalties_text text,
    team_join_date date,
    creativity_rank int,
    dreamteam_count int,
    penalties_order int,
    penalties_saved int,
    points_per_game text,
    expected_assists text,
    penalties_missed int,
    threat_rank_type int,
    cost_change_event int,
    cost_change_start int,
    has_temporary_code boolean,
    now_cost_rank_type int,
    selected_rank_type int,
    transfers_in_event int,
    clean_sheets_per_90 numeric,
    ict_index_rank_type int,
    influence_rank_type int,
    selected_by_percent text,
    transfers_out_event int,
    creativity_rank_type int,
    points_per_game_rank int,
    direct_freekicks_text text,
    expected_goals_per_90 numeric,
    goals_conceded_per_90 numeric,
    cost_change_event_fall int,
    cost_change_start_fall int,
    defensive_contribution int,
    direct_freekicks_order int,
    expected_assists_per_90 numeric,
    expected_goals_conceded text,
    points_per_game_rank_type int,
    expected_goal_involvements text,
    chance_of_playing_next_round int,
    chance_of_playing_this_round int,
    defensive_contribution_per_90 numeric,
    expected_goals_conceded_per_90 numeric,
    clearances_blocks_interceptions int,
    expected_goal_involvements_per_90 numeric,
    corners_and_indirect_freekicks_text text,
    corners_and_indirect_freekicks_order int
)

)

SELECT * fROM elements_