FROM postgres:16

# Set environment variables (optional, can also be set in docker-compose)
# ENV POSTGRES_USER=local_testing
#ENV POSTGRES_PASSWORD=local_testing_password
#ENV POSTGRES_DB=database

#COPY docker/container__postgres/entrypoint_init.sql /docker-entrypoint-initdb.d/
