FROM python:3.12-slim

WORKDIR /opt/app

RUN apt-get update && apt-get install -y \
    openjdk-21-jre \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry

COPY python/etl__project/pyproject.toml python/etl__project/poetry.lock .

RUN poetry install --no-root \
 && rm -rf /root/.cache/pypoetry

COPY python/src .

ENV PYTHONPATH=/opt/app

CMD ["tail", "-f", "/dev/null"]