FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y 

COPY python /app/python

WORKDIR /app/python/etl__project

RUN pip install poetry

RUN poetry install --no-interaction --no-ansi

CMD ["poetry", "run", "python", "-m", "etl.from_faker.to_postgres.dummy_data_generator"]